//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastePermits.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum defra_preapplicationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defra_preapplication")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class defra_preapplication : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defra_agentid = "defra_agentid";
			public const string defra_applicationnumber = "defra_applicationnumber";
			public const string defra_applicationtype = "defra_applicationtype";
			public const string defra_customerid = "defra_customerid";
			public const string defra_deactivatedon = "defra_deactivatedon";
			public const string defra_lastapplicationissuedid = "defra_lastapplicationissuedid";
			public const string defra_name = "defra_name";
			public const string defra_preapplicationId = "defra_preapplicationid";
			public const string Id = "defra_preapplicationid";
			public const string defra_primarycontactid = "defra_primarycontactid";
			public const string defra_siteid = "defra_siteid";
			public const string defra_timespent = "defra_timespent";
			public const string defra_totaltimespent = "defra_totaltimespent";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defra_account_defra_preapplication_agentid = "defra_account_defra_preapplication_agentid";
			public const string defra_account_defra_preapplication_customerid = "defra_account_defra_preapplication_customerid";
			public const string defra_application_defra_preapplication_lastapplicationissuedid = "defra_application_defra_preapplication_lastapplicationissuedid";
			public const string defra_contact_defra_preapplication_agentid = "defra_contact_defra_preapplication_agentid";
			public const string defra_contact_defra_preapplication_customerid = "defra_contact_defra_preapplication_customerid";
			public const string defra_contact_defra_preapplication_primarycontactid = "defra_contact_defra_preapplication_primarycontactid";
			public const string defra_location_defra_preapplication_siteid = "defra_location_defra_preapplication_siteid";
			public const string lk_defra_preapplication_createdby = "lk_defra_preapplication_createdby";
			public const string lk_defra_preapplication_createdonbehalfby = "lk_defra_preapplication_createdonbehalfby";
			public const string lk_defra_preapplication_modifiedby = "lk_defra_preapplication_modifiedby";
			public const string lk_defra_preapplication_modifiedonbehalfby = "lk_defra_preapplication_modifiedonbehalfby";
			public const string team_defra_preapplication = "team_defra_preapplication";
			public const string user_defra_preapplication = "user_defra_preapplication";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public defra_preapplication() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defra_preapplication";
		
		public const string PrimaryIdAttribute = "defra_preapplicationid";
		
		public const string PrimaryNameAttribute = "defra_name";
		
		public const int EntityTypeCode = 10029;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_agentid")]
		public Microsoft.Xrm.Sdk.EntityReference defra_agentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defra_agentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_agentid");
				this.SetAttributeValue("defra_agentid", value);
				this.OnPropertyChanged("defra_agentid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_applicationnumber")]
		public string defra_applicationnumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("defra_applicationnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_applicationnumber");
				this.SetAttributeValue("defra_applicationnumber", value);
				this.OnPropertyChanged("defra_applicationnumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_applicationtype")]
		public Microsoft.Xrm.Sdk.OptionSetValue defra_applicationtype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("defra_applicationtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_applicationtype");
				this.SetAttributeValue("defra_applicationtype", value);
				this.OnPropertyChanged("defra_applicationtype");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_customerid")]
		public Microsoft.Xrm.Sdk.EntityReference defra_customerid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defra_customerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_customerid");
				this.SetAttributeValue("defra_customerid", value);
				this.OnPropertyChanged("defra_customerid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_deactivatedon")]
		public System.Nullable<System.DateTime> defra_deactivatedon
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defra_deactivatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_deactivatedon");
				this.SetAttributeValue("defra_deactivatedon", value);
				this.OnPropertyChanged("defra_deactivatedon");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_lastapplicationissuedid")]
		public Microsoft.Xrm.Sdk.EntityReference defra_lastapplicationissuedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defra_lastapplicationissuedid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_lastapplicationissuedid");
				this.SetAttributeValue("defra_lastapplicationissuedid", value);
				this.OnPropertyChanged("defra_lastapplicationissuedid");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_name")]
		public string defra_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("defra_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_name");
				this.SetAttributeValue("defra_name", value);
				this.OnPropertyChanged("defra_name");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_preapplicationid")]
		public System.Nullable<System.Guid> defra_preapplicationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defra_preapplicationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_preapplicationId");
				this.SetAttributeValue("defra_preapplicationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defra_preapplicationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_preapplicationid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.defra_preapplicationId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_primarycontactid")]
		public Microsoft.Xrm.Sdk.EntityReference defra_primarycontactid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defra_primarycontactid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_primarycontactid");
				this.SetAttributeValue("defra_primarycontactid", value);
				this.OnPropertyChanged("defra_primarycontactid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_siteid")]
		public Microsoft.Xrm.Sdk.EntityReference defra_siteid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defra_siteid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_siteid");
				this.SetAttributeValue("defra_siteid", value);
				this.OnPropertyChanged("defra_siteid");
			}
		}
		
		/// <summary>
		/// Manual entry of time spent giving Pre-Application advice. Should not include time logged automatically in activities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_timespent")]
		public System.Nullable<int> defra_timespent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defra_timespent");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_timespent");
				this.SetAttributeValue("defra_timespent", value);
				this.OnPropertyChanged("defra_timespent");
			}
		}
		
		/// <summary>
		/// Total time spent giving Pre-Application advice. Includes time recorded in activities and manual adjustments.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_totaltimespent")]
		public System.Nullable<int> defra_totaltimespent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defra_totaltimespent");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_totaltimespent");
				this.SetAttributeValue("defra_totaltimespent", value);
				this.OnPropertyChanged("defra_totaltimespent");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Pre-Application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<WastePermits.Model.EarlyBound.defra_preapplicationState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((WastePermits.Model.EarlyBound.defra_preapplicationState)(System.Enum.ToObject(typeof(WastePermits.Model.EarlyBound.defra_preapplicationState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Pre-Application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defra_defra_preapplication_defra_application
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_defra_preapplication_defra_application")]
		public System.Collections.Generic.IEnumerable<WastePermits.Model.EarlyBound.defra_application> defra_defra_preapplication_defra_application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<WastePermits.Model.EarlyBound.defra_application>("defra_defra_preapplication_defra_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_defra_preapplication_defra_application");
				this.SetRelatedEntities<WastePermits.Model.EarlyBound.defra_application>("defra_defra_preapplication_defra_application", null, value);
				this.OnPropertyChanged("defra_defra_preapplication_defra_application");
			}
		}
		
		/// <summary>
		/// 1:N defra_preapplication_defra_facility_preapplicationid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_preapplication_defra_facility_preapplicationid")]
		public System.Collections.Generic.IEnumerable<WastePermits.Model.EarlyBound.defra_facility> defra_preapplication_defra_facility_preapplicationid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<WastePermits.Model.EarlyBound.defra_facility>("defra_preapplication_defra_facility_preapplicationid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_preapplication_defra_facility_preapplicationid");
				this.SetRelatedEntities<WastePermits.Model.EarlyBound.defra_facility>("defra_preapplication_defra_facility_preapplicationid", null, value);
				this.OnPropertyChanged("defra_preapplication_defra_facility_preapplicationid");
			}
		}
		
		/// <summary>
		/// 1:N defra_preapplication_defra_wastetypedetail_preapplicationid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_preapplication_defra_wastetypedetail_preapplicationid")]
		public System.Collections.Generic.IEnumerable<WastePermits.Model.EarlyBound.defra_wastetypedetail> defra_preapplication_defra_wastetypedetail_preapplicationid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<WastePermits.Model.EarlyBound.defra_wastetypedetail>("defra_preapplication_defra_wastetypedetail_preapplicationid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_preapplication_defra_wastetypedetail_preapplicationid");
				this.SetRelatedEntities<WastePermits.Model.EarlyBound.defra_wastetypedetail>("defra_preapplication_defra_wastetypedetail_preapplicationid", null, value);
				this.OnPropertyChanged("defra_preapplication_defra_wastetypedetail_preapplicationid");
			}
		}
		
		/// <summary>
		/// N:N defra_preapplication_defra_standardrule
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_preapplication_defra_standardrule")]
		public System.Collections.Generic.IEnumerable<WastePermits.Model.EarlyBound.defra_standardrule> defra_preapplication_defra_standardrule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<WastePermits.Model.EarlyBound.defra_standardrule>("defra_preapplication_defra_standardrule", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_preapplication_defra_standardrule");
				this.SetRelatedEntities<WastePermits.Model.EarlyBound.defra_standardrule>("defra_preapplication_defra_standardrule", null, value);
				this.OnPropertyChanged("defra_preapplication_defra_standardrule");
			}
		}
		
		/// <summary>
		/// N:1 defra_account_defra_preapplication_agentid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_agentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_account_defra_preapplication_agentid")]
		public WastePermits.Model.EarlyBound.Account defra_account_defra_preapplication_agentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Account>("defra_account_defra_preapplication_agentid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_account_defra_preapplication_agentid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.Account>("defra_account_defra_preapplication_agentid", null, value);
				this.OnPropertyChanged("defra_account_defra_preapplication_agentid");
			}
		}
		
		/// <summary>
		/// N:1 defra_account_defra_preapplication_customerid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_account_defra_preapplication_customerid")]
		public WastePermits.Model.EarlyBound.Account defra_account_defra_preapplication_customerid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Account>("defra_account_defra_preapplication_customerid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_account_defra_preapplication_customerid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.Account>("defra_account_defra_preapplication_customerid", null, value);
				this.OnPropertyChanged("defra_account_defra_preapplication_customerid");
			}
		}
		
		/// <summary>
		/// N:1 defra_application_defra_preapplication_lastapplicationissuedid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_lastapplicationissuedid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_application_defra_preapplication_lastapplicationissuedid")]
		public WastePermits.Model.EarlyBound.defra_application defra_application_defra_preapplication_lastapplicationissuedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.defra_application>("defra_application_defra_preapplication_lastapplicationissuedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_application_defra_preapplication_lastapplicationissuedid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.defra_application>("defra_application_defra_preapplication_lastapplicationissuedid", null, value);
				this.OnPropertyChanged("defra_application_defra_preapplication_lastapplicationissuedid");
			}
		}
		
		/// <summary>
		/// N:1 defra_contact_defra_preapplication_agentid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_agentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_contact_defra_preapplication_agentid")]
		public WastePermits.Model.EarlyBound.Contact defra_contact_defra_preapplication_agentid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_agentid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_contact_defra_preapplication_agentid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_agentid", null, value);
				this.OnPropertyChanged("defra_contact_defra_preapplication_agentid");
			}
		}
		
		/// <summary>
		/// N:1 defra_contact_defra_preapplication_customerid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_contact_defra_preapplication_customerid")]
		public WastePermits.Model.EarlyBound.Contact defra_contact_defra_preapplication_customerid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_customerid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_contact_defra_preapplication_customerid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_customerid", null, value);
				this.OnPropertyChanged("defra_contact_defra_preapplication_customerid");
			}
		}
		
		/// <summary>
		/// N:1 defra_contact_defra_preapplication_primarycontactid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_primarycontactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_contact_defra_preapplication_primarycontactid")]
		public WastePermits.Model.EarlyBound.Contact defra_contact_defra_preapplication_primarycontactid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_primarycontactid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_contact_defra_preapplication_primarycontactid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.Contact>("defra_contact_defra_preapplication_primarycontactid", null, value);
				this.OnPropertyChanged("defra_contact_defra_preapplication_primarycontactid");
			}
		}
		
		/// <summary>
		/// N:1 defra_location_defra_preapplication_siteid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_siteid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defra_location_defra_preapplication_siteid")]
		public WastePermits.Model.EarlyBound.defra_location defra_location_defra_preapplication_siteid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.defra_location>("defra_location_defra_preapplication_siteid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("defra_location_defra_preapplication_siteid");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.defra_location>("defra_location_defra_preapplication_siteid", null, value);
				this.OnPropertyChanged("defra_location_defra_preapplication_siteid");
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_preapplication_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_preapplication_createdby")]
		public WastePermits.Model.EarlyBound.SystemUser lk_defra_preapplication_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_preapplication_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_preapplication_createdonbehalfby")]
		public WastePermits.Model.EarlyBound.SystemUser lk_defra_preapplication_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_defra_preapplication_createdonbehalfby");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_defra_preapplication_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_preapplication_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_preapplication_modifiedby")]
		public WastePermits.Model.EarlyBound.SystemUser lk_defra_preapplication_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_preapplication_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_preapplication_modifiedonbehalfby")]
		public WastePermits.Model.EarlyBound.SystemUser lk_defra_preapplication_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_defra_preapplication_modifiedonbehalfby");
				this.SetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("lk_defra_preapplication_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_defra_preapplication_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 team_defra_preapplication
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_defra_preapplication")]
		public WastePermits.Model.EarlyBound.Team team_defra_preapplication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.Team>("team_defra_preapplication", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defra_preapplication
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defra_preapplication")]
		public WastePermits.Model.EarlyBound.SystemUser user_defra_preapplication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<WastePermits.Model.EarlyBound.SystemUser>("user_defra_preapplication", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public defra_preapplication(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["defra_preapplicationid"] = base.Id;
                        break;
                    case "defra_preapplicationid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_applicationtype")]
		public virtual defra_ApplicationType? defra_applicationtypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((defra_ApplicationType?)(EntityOptionSetEnum.GetEnum(this, "defra_applicationtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				defra_applicationtype = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defra_preapplication_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((defra_preapplication_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}