//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lp.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9340")]
	public enum defra_organisation_type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Limitedcompany = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Limitedliabilitypartnership = 910400005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Localauthorityorpublicbody = 910400002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Otherorganisationforexampleacluborassociation = 910400006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partnership = 910400003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Registeredcharity = 910400004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Soletrader = 910400001,
	}
}