//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lp.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum defra_log_defra_importance
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Critical = 910400003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		High = 910400002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Low = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Medium = 910400001,
	}
}