//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lp.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum Incident_CaseTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Problem = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Question = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Request = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RFI = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Schedule5 = 910400001,
	}
}