//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lp.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9340")]
	public enum SyncError_ErrorType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conflict = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Others = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordalreadyexists = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordnotfound = 1,
	}
}