//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastePermits.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum Account_defra_companyhousestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 910400009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertedClosed = 910400004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dissolved = 910400001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InAdministration = 910400007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InsolvencyProceedings = 910400006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Liquidation = 910400002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 910400008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReceiverAction = 910400003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VoluntaryArrangement = 910400005,
	}
}