//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastePermits.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum defra_application_defra_technicalability
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Deemedcompetence = 910400002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ESAEUSkills = 910400003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualificationWAMITAB = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Registeredonacoursegraceperiod = 910400001,
	}
}