//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastePermits.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum defra_log_defra_nextaction
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 910400000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolve = 910400002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Review = 910400001,
	}
}