//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WastePermits.Model.EarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum SavedQueryVisualization_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		fordatacentricaswellasinteractioncentric = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		justforinteractioncentric = 1,
	}
}