// <copyright file="CompaniesHouseValidation.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>12/4/2017 12:00:54 PM</date>
// <summary>Implements the CompaniesHouseValidation Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.Activities;
using System.Collections.Generic;
using System.Net;
using CardPayments;
using CardPayments.Model;
using Core.Configuration;
using Defra.Lp.Core.CardPayments.Workflow.Constants;
using Defra.Lp.Core.Workflows.CompaniesHouse;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Workflow;
using Defra.Lp.Core.CardPayments.Workflow;
using Defra.Lp.Core.CardPayments.Workflow.CodeActivities.Abstract;

namespace Defra.Lp.Core.CardPayments.Workflow.CodeActivities
{

    /// </summary>    
    public class FindPayment : PaymentWorkflowActivityBase
    {
        // Input Parameters

        [Input("LookupPaymentId")]
        public InArgument<string> LookupPaymentId { get; set; }

        [Input("LookupPaymentReferenceNumber")]
        public InArgument<string> LookupPaymentReferenceNumber { get; set; }


        /// <summary>
        /// Executes the WorkFlow.
        /// </summary>
        /// <param name="crmWorkflowContext">The <see cref="WorkFlowActivityBase.LocalWorkflowContext"/> which contains the
        /// <param name="executionContext" > <see cref="CodeActivityContext"/>
        /// </param>       
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches WorkFlow instances.
        /// The WorkFlow's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the WorkFlow. Also, multiple system threads
        /// could execute the WorkFlow at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in WorkFlows.
        /// </remarks>
        public override void ExecuteCRMWorkFlowActivity(CodeActivityContext executionContext, LocalWorkflowContext crmWorkflowContext)
        {
            var tracingService = executionContext.GetExtension<ITracingService>();
            tracingService.Trace("FindPayment starting...");

            try
            {
                // 1. Validation
                ValidateNotNull(crmWorkflowContext);

                // 2. Prepare API Request
                tracingService.Trace("Calling PrepareCardPaymentRequest...");
                FindPaymentRequest apiRequest = this.PrepareFindPaymentRequest(executionContext, crmWorkflowContext, tracingService);

                // 3. Retrieve Configuration
                tracingService.Trace("Calling RetrieveCardPaymentServiceConfiguration...");
                RestServiceConfiguration cardServiceConfiguration = this.RetrieveCardPaymentServiceConfiguration(crmWorkflowContext.OrganizationService, ConfigurationPrefix.Get(executionContext));

                // 4. Set-up the Api Service
                tracingService.Trace("Instantiating CardPaymentService...");
                CardPaymentService cardPaymentService = new CardPaymentService(cardServiceConfiguration);

                // 5. Call the API
                tracingService.Trace("Calling GovPay CreatePayment...");
                FindPaymentResponse apiResponse = cardPaymentService.FindPayment(apiRequest);

                // 6. Return the response
                tracingService.Trace("Calling PrepareOutputParameters...");
                this.PrepareOutputParameters(executionContext, apiResponse, tracingService);

            }
            catch (Exception ex)
            {
                // Todo: Log the Error
                tracingService.Trace("Exception: " + ex);
                throw ex;
            }
        }



        private FindPaymentRequest PrepareFindPaymentRequest(CodeActivityContext executionContext, LocalWorkflowContext crmWorkflowContext, ITracingService tracingService)
        {
            
            string paymentId = LookupPaymentId.Get(executionContext);
            tracingService.Trace("PrepareFindPaymentRequest trying paymentId: {0}", paymentId);

            if (string.IsNullOrWhiteSpace(paymentId))
            {
                string paymentRefNum = LookupPaymentReferenceNumber.Get(executionContext);
                tracingService.Trace("PrepareFindPaymentRequest trying paymentRefNum: {0}", paymentRefNum);

                // Try to get the payment id from the Payment reference number
                paymentId = crmWorkflowContext.OrganizationService.GetPaymentIdFromPaymentReferenceNumber(paymentRefNum, tracingService);
            }

            if (string.IsNullOrWhiteSpace(paymentId))
            {
                tracingService.Trace("PrepareFindPaymentRequest Could not find payment id, returning {0}", paymentId);
                throw new ArgumentException("paymentRefNum");
            }

            tracingService.Trace("PrepareFindPaymentRequest using paymentId: {0}", paymentId);


            FindPaymentRequest apiRequest = new FindPaymentRequest
            {
                PaymentId = paymentId
            };
            return apiRequest;
        }
    }
}